const express = require("express");
const controller = require("../Controller/AdminController");
const { authenticate, allowRoles } = require("../middleware/auth");
const upload = require("../middleware/upload");
const router = express.Router();

router.post("/login", controller.login);
router.use(authenticate, allowRoles("admin"));
router.get("/profile", controller.profile);
router.patch("/profile", controller.updateProfile);
router.get("/dashboard", controller.dashboard);
router.get("/users", controller.users);
router.get("/users/:id", controller.user);
router.patch("/users/:id/status", controller.changeUserStatus);
router.delete("/users/:id", controller.deleteUser);
router.get("/freelancers", controller.freelancers);
router.get("/clients", controller.clients);
router.get("/projects", controller.projects);
router.post("/projects", upload.single("image"), controller.createProject);
router.put("/projects/:id", upload.single("image"), controller.updateProject);
router.delete("/projects/:id", controller.deleteProject);
router.get("/proposals", controller.proposals);
router.patch("/proposals/:id/status", controller.updateProposalStatus);
router.get("/payments", controller.payments);
router.patch("/payments/:id/status", controller.updatePaymentStatus);
router.get("/reviews", controller.reviews);
router.get("/messages", controller.messages);
router.get("/activity", controller.activity);
module.exports = router;
