const categories = ["Software Development", "Design & Creative", "Writing & Translation"];
const locations = ["Anywhere in Somalia", "Mogadishu", "Hargeisa", "Garowe", "Kismayo", "Baidoa", "Beledweyne"];

export default function FilterSidebar({ open, selectedCategories, location, minRate, maxRate, onToggleCategory, onLocationChange, onMinRateChange, onMaxRateChange, onClear, onClose }) {
  return <aside id="categories" className={`${open ? "fixed inset-x-4 top-20 z-40 block max-h-[calc(100vh-6rem)] overflow-y-auto shadow-xl" : "hidden"} rounded-xl border border-slate-200 bg-white p-5 md:static md:block md:max-h-none md:w-48 md:shrink-0 md:self-start md:overflow-visible md:shadow-sm lg:w-60`}>
    <div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Filters</h2><button onClick={onClose} className="text-sm font-semibold text-blue-800 md:hidden">Close</button></div>
    <div className="mt-5 border-t border-slate-100 pt-5"><h3 className="text-sm font-semibold text-slate-800">Category</h3><div className="mt-3 space-y-3">{categories.map((category) => <label key={category} className="flex cursor-pointer items-start gap-2 text-sm text-slate-600"><input type="checkbox" checked={selectedCategories.includes(category)} onChange={() => onToggleCategory(category)} className="mt-0.5 h-4 w-4 rounded accent-blue-700" />{category}</label>)}</div></div>
    <div className="mt-6 border-t border-slate-100 pt-5"><label className="block text-sm font-semibold text-slate-800">Location<select value={location} onChange={(event) => onLocationChange(event.target.value)} className="mt-3 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal text-slate-600 outline-none">{locations.map((place) => <option key={place}>{place}</option>)}</select></label></div>
    <div className="mt-6 border-t border-slate-100 pt-5"><h3 className="text-sm font-semibold text-slate-800">Hourly Rate</h3><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs text-slate-500">Min<input value={minRate} onChange={(event) => onMinRateChange(event.target.value)} type="number" min="0" placeholder="$" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none" /></label><label className="text-xs text-slate-500">Max<input value={maxRate} onChange={(event) => onMaxRateChange(event.target.value)} type="number" min="0" placeholder="$" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none" /></label></div></div>
    <button onClick={onClear} className="mt-6 w-full rounded-lg border border-blue-700 py-2.5 text-sm font-semibold text-blue-800 transition hover:bg-blue-700 hover:text-white">Clear Filters</button>
  </aside>;
}
