import { useState } from "react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { BarChart3, Bell, BriefcaseBusiness, ClipboardList, CreditCard, FileWarning, LayoutDashboard, LogOut, Menu, MessageSquare, Settings, Star, UserRound, Users, X } from "lucide-react";
import { useAuth } from "../context/auth";

const links = [
  ["Dashboard", "/admin/dashboard", LayoutDashboard], ["All users", "/admin/users", Users], ["Freelancers", "/admin/freelancers", Users], ["Clients", "/admin/clients", Users],
  ["Projects", "/admin/projects", BriefcaseBusiness], ["Proposals", "/admin/proposals", ClipboardList], ["Messages", "/admin/messages", MessageSquare], ["Payments", "/admin/payments", CreditCard],
  ["Reviews & ratings", "/admin/reviews", Star], ["Reports", "/admin/reports", FileWarning], ["Activity log", "/admin/activity", BarChart3], ["Settings", "/admin/settings", Settings],
];
export default function AdminLayout() {
  const [open, setOpen] = useState(false); const { user, logout } = useAuth(); const navigate = useNavigate();
  const sidebar = <aside className="flex h-full w-72 flex-col bg-gradient-to-b from-[#173a9f] via-[#2C65F4] to-[#10245f] px-4 py-6 text-blue-50"><div className="mb-9 flex items-center gap-3 px-2"><Link to="/" className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-blue-100 font-black text-[#2C65F4]">FH</div><div><p className="font-bold text-white">Freelancer Hub</p><p className="text-xs text-blue-100">Somalia Administration</p></div></Link><button className="ml-auto md:hidden" onClick={() => setOpen(false)}><X /></button></div><nav className="space-y-1 overflow-y-auto">{links.map(([label, to, Icon]) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({isActive}) => `flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${isActive ? "bg-white/20 text-white shadow-sm" : "hover:bg-white/10 hover:text-white"}`}><Icon size={18}/>{label}</NavLink>)}</nav><div className="mt-auto border-t border-white/15 pt-4"><button onClick={() => { logout(); navigate("/admin/login"); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium hover:bg-white/10"><LogOut size={18}/>Logout</button></div></aside>;
  return <div className="admin-shell min-h-screen bg-slate-50"><div className="fixed inset-y-0 left-0 z-40 hidden md:block">{sidebar}</div>{open && <div className="fixed inset-0 z-50 bg-slate-950/50 md:hidden"><div className="h-full w-72">{sidebar}</div></div>}<main className="md:ml-72"><header className="flex h-18 items-center justify-between border-b border-slate-200 bg-white px-5 py-4"><button className="md:hidden" onClick={() => setOpen(true)}><Menu /></button><div className="hidden md:block"><p className="text-sm text-slate-500">Platform control centre</p></div><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Bell size={19}/></button><Link to="/admin/settings" aria-label="Admin account settings" className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 text-blue-700 hover:bg-blue-200"><UserRound size={19}/></Link></div></header><div className="p-5 md:p-8"><Outlet /></div></main></div>;
}
