import { useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/auth";
export default function AdminLogin() { const [form,setForm]=useState({identity:"admin",password:"Admin@12345"}); const [show,setShow]=useState(false); const [remember,setRemember]=useState(true); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const {login}=useAuth(); const navigate=useNavigate();
 const submit=async(e)=>{e.preventDefault();setError("");setLoading(true);try{const {data}=await axios.post("http://localhost:5000/api/admin/login",form);login(data);if(!remember) sessionStorage.setItem("admin-session","true");navigate("/admin/dashboard");}catch(err){setError(err.response?.data?.message||"Unable to sign in. Try again.");}finally{setLoading(false);}};
 return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-blue-50 via-indigo-50 to-blue-100 px-4 py-8"><section className="w-full max-w-md rounded-3xl bg-white px-7 py-8 text-center shadow-[0_20px_45px_rgba(44,101,244,0.18)] sm:px-9"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-blue-100 text-2xl font-extrabold text-[#2C65F4]">FH</div><h1 className="mt-4 text-3xl font-extrabold tracking-tight text-[#163781]">Freelancer Hub</h1><p className="mt-1 text-base text-slate-500">Somalia Administration</p><form className="mx-auto mt-7 space-y-4 text-left" onSubmit={submit}><label className="sr-only">Email or username</label><input aria-label="Email or username" required value={form.identity} onChange={e=>setForm({...form,identity:e.target.value})} placeholder="Email or username" className="w-full rounded-xl border border-blue-200 bg-slate-100 px-4 py-3 text-base text-slate-900 outline-none transition placeholder:text-slate-500 focus:border-[#2C65F4] focus:bg-white focus:ring-4 focus:ring-blue-100" /><label className="sr-only">Password</label><div className="relative"><input aria-label="Password" required type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Password" className="w-full rounded-xl border border-blue-200 bg-slate-100 px-4 py-3 pr-12 text-base text-slate-900 outline-none transition placeholder:text-slate-500 focus:border-[#2C65F4] focus:bg-white focus:ring-4 focus:ring-blue-100"/><button type="button" aria-label={show?"Hide password":"Show password"} onClick={()=>setShow(!show)} className="absolute right-4 top-3 text-slate-500 hover:text-[#2C65F4]">{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="h-4 w-4 accent-[#2C65F4]"/>Remember me</label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-gradient-to-r from-[#2C65F4] to-blue-800 py-3.5 text-base font-bold text-white shadow-sm transition hover:from-blue-600 hover:to-blue-900 disabled:opacity-60">{loading?"Logging in…":"Login"}</button></form><p className="mt-6 text-xs text-slate-500">Administrator access only</p></section></main>;
}
